// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name) 
VALUES ($1) 
RETURNING id, name, stripe_customer_id, metadata, created_at, updated_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StripeCustomerID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (org_id, name, description, price_cents, inventory_count, attributes) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, org_id, name, description, price_cents, inventory_count, attributes, created_at, updated_at
`

type CreateProductParams struct {
	OrgID          uuid.UUID             `json:"org_id"`
	Name           string                `json:"name"`
	Description    string                `json:"description"`
	PriceCents     int64                 `json:"price_cents"`
	InventoryCount int32                 `json:"inventory_count"`
	Attributes     pqtype.NullRawMessage `json:"attributes"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.InventoryCount,
		arg.Attributes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.InventoryCount,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, org_id, role) 
VALUES ($1, $2, $3, $4) 
RETURNING id, email, org_id, role, metadata, created_at, updated_at
`

type CreateUserParams struct {
	ID    string        `json:"id"`
	Email string        `json:"email"`
	OrgID uuid.NullUUID `json:"org_id"`
	Role  string        `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.OrgID,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrgID,
		&i.Role,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, org_id, name, description, price_cents, inventory_count, attributes, created_at, updated_at FROM products 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.InventoryCount,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsByOrg = `-- name: ListProductsByOrg :many
SELECT id, org_id, name, description, price_cents, inventory_count, attributes, created_at, updated_at FROM products 
WHERE org_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListProductsByOrg(ctx context.Context, orgID uuid.UUID) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.InventoryCount,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
