// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Address struct {
	ID         uuid.UUID      `json:"id"`
	UserID     string         `json:"user_id"`
	Type       string         `json:"type"`
	Line1      string         `json:"line1"`
	Line2      sql.NullString `json:"line2"`
	City       string         `json:"city"`
	State      string         `json:"state"`
	PostalCode string         `json:"postal_code"`
	Country    string         `json:"country"`
	IsDefault  bool           `json:"is_default"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Order struct {
	ID             uuid.UUID      `json:"id"`
	OrgID          uuid.UUID      `json:"org_id"`
	UserID         string         `json:"user_id"`
	Status         string         `json:"status"`
	TotalCents     int64          `json:"total_cents"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type OrderLineItem struct {
	ID             uuid.UUID `json:"id"`
	OrderID        uuid.UUID `json:"order_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Quantity       int32     `json:"quantity"`
	UnitPriceCents int64     `json:"unit_price_cents"`
	CreatedAt      time.Time `json:"created_at"`
}

type Organization struct {
	ID               uuid.UUID             `json:"id"`
	Name             string                `json:"name"`
	StripeCustomerID sql.NullString        `json:"stripe_customer_id"`
	Metadata         pqtype.NullRawMessage `json:"metadata"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   string          `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	ProcessedAt   sql.NullTime    `json:"processed_at"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Product struct {
	ID             uuid.UUID             `json:"id"`
	OrgID          uuid.UUID             `json:"org_id"`
	Name           string                `json:"name"`
	Description    string                `json:"description"`
	PriceCents     int64                 `json:"price_cents"`
	InventoryCount int32                 `json:"inventory_count"`
	Attributes     pqtype.NullRawMessage `json:"attributes"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type User struct {
	ID        string                `json:"id"`
	Email     string                `json:"email"`
	OrgID     uuid.NullUUID         `json:"org_id"`
	Role      string                `json:"role"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
}
