// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	ListProductsByOrg(ctx context.Context, orgID uuid.UUID) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
